---
title: Liga Canotaje Bogotá D.C.
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: canotaje@canotajebogota.com
description: "¡Bienvenido a la página oficial de la Liga de Canotaje de Bogotá!  Sumérgete
  en el fascinante mundo del remo en la capital de Colombia y  descubre emocionantes
  actividades acuáticas para todas las edades.  Nuestra liga está dedicada a fomentar
  la pasión por el canotaje,  brindando oportunidades para competidores y entusiastas
  por igual.  Explora nuestras instalaciones de vanguardia, conoce a nuestros  talentosos
  atletas y únete a una comunidad apasionada por la vida en el agua.  ¡Descubre cómo
  puedes embarcarte en una emocionante aventura acuática con la Liga de Canotaje de
  Bogotá hoy mismo!"
social:
- title: facebook
  url: https://www.facebook.com/ligadecanotajebogota/
- title: twitter
  url: https://twitter.com/canotajedc
- title: instagram
  url: https://www.instagram.com/canotaje_dc/
address:
- line: Av Caracas \# 39 - 18 Apto 610
- line: Bogotá, Colombia
markdown: kramdown
permalink: pretty
